language: php
php:
  - 7.4
before_script:
  - travis_retry composer self-update
install:
  - COMPOSER_ALLOW_XDEBUG=0 composer install --prefer-dist --no-interaction
  - npm install
#  - composer install --prefer-dist --no-interaction
script:
#  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpunit
  - npm run gulp
#  - vendor/bin/php-cs-fixer fix --dry-run
#  - vendor/bin/phpstan analyze -l 3 src
#  - vendor/bin/phpstan analyze tests
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
